default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password: password
  host: localhost
  port: 3306
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: app_db

test:
  <<: *default
  database: app_db_test
