---
- hosts: all

  vars_files:
    - vars/global.yml
    - vars/aws.yml

  vars:
    apt_packages:
      - curl
      - git
      - build-essential
      - libcurl4-openssl-dev
      - libxslt-dev
      - libxml2-dev
      - libpq-dev
      - libmysqlclient-dev
      - sendmail
      - imagemagick

    provisioner_path: ../provisioner/roles

  roles:
    - "{{ provisioner_path }}/base"
    - "{{ provisioner_path }}/ruby"
    - "{{ provisioner_path }}/nginx"
    - "{{ provisioner_path }}/nodejs"
    - "{{ provisioner_path }}/rails-capistranofied-setup"
    - "{{ provisioner_path }}/unicorn-config"
