---
- hosts: all

  vars_files:
    - vars/global.yml
    - vars/vagrant.yml

  vars:
    provisioner_path: ../provisioner/roles
# sudo apt-get install libmysqlclient-dev
# sudo apt-get install build-essential
# sudo apt-get install libpq-dev

  roles:
    - "{{ provisioner_path }}/base"
    - "{{ provisioner_path }}/mysql"
    - "{{ provisioner_path }}/ruby"
    - "{{ provisioner_path }}/nginx"
    - "{{ provisioner_path }}/nodejs"
    - "{{ provisioner_path }}/unicorn-config"
    - "{{ provisioner_path }}/redis"
